### Base URL
@baseUrl = http://localhost:5000


### Store token manually after login
@token = token



### Submit Claim

POST http://localhost:5000/api/claims
Authorization: Bearer token
Content-Type: multipart/form-data

name=John Patient
email=john@gmail.com
claimAmount=5000
description=Medical treatment reimbursement claim
document=@./receipt.pdf


# 3. Get My Claims

GET {{baseUrl}}/api/claims/my
Authorization: Bearer {{token}}


### Get All Claims
GET {{baseUrl}}/api/claims
Authorization: Bearer token


### Filter by Status
GET {{baseUrl}}/api/claims?status=PENDING
Authorization: Bearer token


### Filter by Minimum Amount
GET {{baseUrl}}/api/claims?minAmount=5000
Authorization: Bearer token


### Filter by Maximum Amount
GET {{baseUrl}}/api/claims?maxAmount=10000
Authorization: Bearer token


### Filter by Date Range
GET {{baseUrl}}/api/claims?startDate=2026-07-01&endDate=2026-07-31
Authorization: Bearer token